compose:
  DpInComposable:
    active: true
  MissingDefaultModifier:
    active: true
  NoMutableStateParameter:
    active: true
  RememberMutableState:
    active: true
kotlin:
  LargeClass:
    active: true